version: "1.0"
catalog:
  agents:
    sources:
      - type: directory
        path: agents
      - type: directory
        path: .ai-catalog/agents
      - type: directory
        path: .gitlab/agents
      - type: directory
        path: .gitlab/duo
  flows:
    sources:
      - type: directory
        path: flows
      - type: directory
        path: .ai-catalog/flows
      - type: directory
        path: .gitlab/flows
      - type: directory
        path: .gitlab/duo
